### ISSUE TITLE
About running result

### ISSUE THREAD

**Issue by zhangyedi** [teobaluta/NPAQ#19]
Hi, can you tell me how to compute "the percentage of individuals classified as having the same annual income" in fairness checking after I run the command. Now I can only get some log files and formula_cam_ready files. 

And the same question for other properties checking results. Thanks! :)

**Comment by teobaluta** [comment]
Hi, 

The tool outputs counts, not percentages -- we calculated percentages when presenting the results in the paper. You can get those percentages if you divide the count by the total input space.

#### 1) Robustness
For robustness, the output is printed out:
> Model filename: mnist-100-bnn_1blk_100
Log Dir -> /hdd/NPAQ/npaq/../logs/mnist_robustness
npaq/models/bnn.py:227: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return self.logsoftmax(x)
Started counting over /hdd/NPAQ/npaq/../formulas_cam_ready/best-mnist-100-bnn_1blk_100-robustness-perturb_2-id_0.dimacs
('/hdd/NPAQ/npaq/../formulas_cam_ready/best-mnist-100-bnn_1blk_100-robustness-perturb_2-id_0.dimacs', '80 x 2^4')
Counting done. Saving witnesses...

The results are saved in the `output_approxmc` folder -- check out the files `mnist-100-bnn_1blk_100-perturb_2.csv` and `mnist-100-bnn_1blk_100-perturb_2.csv` for the counting part.

In this use case, the input space is 100 choose 2 = 4950.

#### 2) Trojan success
The output is printed to stdout and in the folder `output_approxmc` (similar files to robustness). The input space is 2^96 as the trigger is 4 bits.

#### 3) Fairness
There are some extra constraints we had to add for the UCI Adult dataset that I have posted on the project page. We calculated the input space based on those constraints (so it is not all 2^66 bits combinations because there are certain combinations that are not permitted).

* how many people with ‘Divorced’ vs ‘Married-civ-spouse’ (where all the other features are kept the same) with have different incomes/predictions
f(x1 x2 … ‘D’ … xn) = y1 and f(x1 x2 … ‘M’ … xn) = y2 and y1 != y2
#(all solutions) = 8 * 8 * (2^10) * 16 * 1 * 14 * 6 * 5 * 2 * (2^10) * (2^9) * (2^7) * 41
* how many people with ‘White’ vs ‘Black’ (where all the other features are kept the same) with have different incomes/predictions
#(all solutions) = 8 * 8 * (2^10) * 16 * 7 * 14 * 6 * 1 * 2 * (2^10) * (2^9) * (2^7) * 41
how many people with ‘Female’ vs ‘Male’ (where all the other features are kept the same) with have different incomes/predictions
#(all solutions) = 8 * 8 * (2^10) * 16 * 7 * 14 * 6 * 5 * 1 * (2^10) * (2^9) * (2^7) * 41

Constraints specific to UCI Dataset
- workclass: 8 values, 3 bits => no need to add constraints, all inputs are valid inputs
- education: 16 values, 4 bits => no need for constraints
- marital: 7 values, 3 bits => add constraint 111 not VALID input
[‘Married-civ-spouse’, ‘Divorced’, ‘Never-married’, ‘Separated’, ‘Widowed’, ‘Married-spouse-absent’, ‘Married-AF-spouse’]
- occupation: 14 values, 4 bits => add constraint for last 2 values 110, 111
- relationship: 6 values, 3 bits => add constraint for last 2 values 110, 111
- race: 5 values, 3 bits => add constraints for last 3 values
- country: 41 values, 6 bits => add constraints

For fairness and trojan attack, `approxmc` does not run directly. I will add that to the code asap.

**Comment by zhangyedi** [comment]
Thanks!!!
